backend:
  name: git-gateway
  branch: main
media_folder: "/assets/uploads"
site_url: https://adalbertolonardi.com
show_preview_links: false
collections:
  - name: "settings"
    label: "Settings"
    preview: false
    files:
      - file: "_data/settings.json"
        name: "settings"
        label: "Site Settings"
        fields:
          - label: "Site Title"
            name: "site_title"
            widget: "string"
          - label: "Site Description"
            name: "site_description"
            widget: "string"
            hint: "This is displayed in the header and social media cards."
          - label: "Featured Projects"
            name: "featured_projects"
            hint: "Featured projects appear on the homepage."
            widget: "relation"
            collection: "projects"
            value_field: "title"
            search_fields: ["title"]
            multiple: true
          - label: "Show the projects archive?"
            name: "show_archive"
            widget: "boolean"
            default: false
          - label: "Copyright Notice"
            name: "copyright_text"
            widget: "string"
          - label: "Meta Title"
            name: "meta_title"
            widget: "string"
            hint: "This will be appear in search results."
          - label: "Meta Description"
            name: "meta_description"
            widget: "string"
            hint: "This might appear in search results."
      - file: "_data/about.json"
        name: "about"
        label: "Information"
        fields:
          - label: "Copy"
            name: "content"
            widget: "markdown"
          - label: "Clients and Collaborators"
            name: "clients"
            widget: "list"
            hint: "Separate multiple entries by comma."
          - label: Information Blocks
            name: widgets
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - {
                  name: text,
                  label: Text,
                  widget: markdown,
                  buttons: [bold, italic, link, heading-two, bulleted-list],
                  editor_components: [],
                }
  - name: "projects"
    preview: false
    label: "Projects"
    folder: "projects/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "project"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Start Year"
        name: "start_year"
        widget: "number"
        default: 2020
        value_type: "int"
      - label: "End Year"
        name: "end_year"
        widget: "number"
        default: 2020
        value_type: "int"
      - label: "Description"
        name: "body"
        widget: markdown
        buttons:
          [
            bold,
            italic,
            link,
            heading-two,
            heading-three,
            heading-four,
            bulleted-list,
            numbered-list,
          ]

      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Separate multiple tags by comma."
      - label: Featured Image
        name: featured_image
        widget: object
        summary: "{{fields.url}}"
        fields:
          - label: Landscape Image
            name: landscape
            widget: "image"
          - label: Portrait Image
            name: portrait
            widget: "image"
          - label: Description
            name: alt
            widget: "string"
      - label: "Project Media"
        name: "media"
        widget: "list"
        summary: "{{fields.url}}"
        fields:
          - label: Image
            name: url
            widget: "image"
          - label: Caption
            name: caption
            widget: string
          - label: "Description"
            name: "alt"
            widget: "text"
            hint: "You can add a description to your media items so they’re accessible to more people, including those who are blind or visually impaired. Good descriptions are concise, but present what’s in your photos accurately enough to understand their context."
