backend:
  name: git-gateway
  branch: main
media_folder: "/assets/uploads"
site_url: https://adalbertolonardi.com
show_preview_links: false
collections:
  - name: "settings"
    label: "Settings"
    editor: { preview: false }
    files:
      - file: "_data/settings.json"
        name: "settings"
        label: "Site Settings"
        fields:
          - label: "Site Title"
            name: "site_title"
            widget: "string"
          - label: "Site Description"
            name: "site_description"
            widget: "string"
            hint: "This is displayed in the header."
          - label: "Homepage Projects"
            name: "featured_projects"
            hint: "These projects will appear in the homepage slider."
            widget: "relation"
            collection: "projects"
            value_field: "title"
            search_fields: ["title"]
            multiple: true
          - label: "Archive Projects"
            name: "projects"
            hint: "These projects will appear on the Projects page in the ."
            widget: "ncw-reorder"
            collection: "projects"
            id_field: "title"
            display_template: "{{title}} ({{end_year}})"
          - label: "Show the projects archive?"
            name: "show_archive"
            widget: "boolean"
            default: false
          - label: "Copyright Notice"
            name: "copyright_text"
            widget: "string"
          - label: "Meta Title"
            name: "meta_title"
            widget: "string"
            hint: "This will be appear in search results and social media cards."
          - label: "Meta Description"
            name: "meta_description"
            widget: "string"
            hint: "This might appear in search results and social media cards."
          - label: "Social Media Image"
            name: "social_image"
            widget: "image"
            hint: "Might appear in social media cards."
      - file: "_data/about.json"
        name: "about"
        label: "Information"
        fields:
          - label: "Copy"
            name: "content"
            widget: "markdown"
          - label: "Sidebar A Items"
            name: "sidebar_a"
            widget: "list"
            label_singular: Sidebar Item
            fields:
              - name: title
                label: Title
                widget: string
              - name: text
                label: Text
                widget: markdown
                buttons:
                  - bold
                  - italic
                  - link
                  - heading-two
                  - bulleted-list
                editor_components: []
          - label: Sidebar B Items
            label_singular: Sidebar Item
            name: widgets
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - {
                  name: text,
                  label: Text,
                  widget: markdown,
                  buttons: [bold, italic, link, heading-two, bulleted-list],
                  editor_components: [],
                }
  - name: "projects"
    label: "Projects"
    editor: { preview: false }
    folder: "projects/"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "project"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: Is this a draft?
        name: draft
        widget: boolean
        hint: "Draft projects won't appear in the projects oveview and related projects, but can still be accessed through a direct link."
      - label: "Subtitle"
        name: "subtitle"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Start Year"
        name: "start_year"
        widget: "number"
        default: 2020
        value_type: "int"
      - label: "End Year"
        name: "end_year"
        widget: "number"
        default: 2020
        value_type: "int"
      - label: "Description"
        name: "body"
        widget: markdown
        buttons:
          [
            bold,
            italic,
            link,
            heading-two,
            heading-three,
            heading-four,
            bulleted-list,
            numbered-list,
          ]
      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Separate multiple tags by comma."
      - label: Featured Image
        name: featured_image
        widget: object
        summary: "{{fields.url}}"
        fields:
          - label: Landscape Image
            name: landscape
            widget: "image"
            media_library:
              config:
                max_file_size: 6000000
          - label: Portrait Image
            name: portrait
            widget: "image"
            media_library:
              config:
                max_file_size: 6000000
          - label: Alt text
            name: alt
            widget: "string"
          - label: Is this a light image?
            name: light_image
            widget: boolean
            hint: If yes, we'll switch the navigation colour on the homepage
      - label: Related Projects
        name: related_projects
        widget: "relation"
        collection: projects
        value_field: title
        search_fields: ["title"]
        display_fields: ["title"]
        multiple: true
        required: false